In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("./risultati_gen_GPT4.1_con_judge.csv")

In [4]:
for row in df.itertuples():
    if row.judge_score < 0.5:
        print(f"index: {row.Index}, Question: {row.question},\nDifficulty: {row.difficulty}")

index: 11, Question: Qual è il costo medio di produzione di un H-Node Edge dotato di micro-controller ARM Cortex-M33 e Secure Enclave?,
Difficulty: impossibile
index: 15, Question: Qual è il costo medio di implementazione di un modulo Pulse Master su ciascun H-Node in una micro-rete energetica conforme alle policy Kyoto 2.0?,
Difficulty: impossibile
index: 59, Question: Qual è la versione minima di MATLAB/Simulink richiesta per garantire la compatibilità con i moduli digital twin H-Node nel framework di simulazione AETERNA?,
Difficulty: impossibile
index: 64, Question: Quale tipo di autenticazione multifattoriale è richiesto per un amministratore nella piattaforma AETERNA?,
Difficulty: facile
index: 80, Question: Quali sono i tre organi principali che formalizzano la governance della rete AETERNA?,
Difficulty: facile
index: 131, Question: Qual è il costo medio di implementazione per nodo degli agenti di telemetria containerizzati nel Progetto AETERNA, considerando sia la componente hardware che quella software?,
Difficulty: impossibile
index: 132, Question: Quale standard viene utilizzato per la normalizzazione dei dati nella fase di pre-processing della pipeline di analisi predittiva dei guasti in AETERNA?,
Difficulty: facile
index: 155, Question: Qual è il costo medio di implementazione per nodo domestico (H-Node) dei sensori IoT multi-parametrici utilizzati nel Progetto AETERNA?,
Difficulty: impossibile
index: 156, Question: Quale piattaforma viene utilizzata per la raccolta e gestione dei ticket di supporto nel Progetto AETERNA?,
Difficulty: facile
index: 160, Question: Quale strumento viene utilizzato per automatizzare i test sulle API RESTful nella piattaforma AETERNA?,
Difficulty: facile
index: 176, Question: Quale strumento viene utilizzato per il caching distribuito dei dati ad alta frequenza di accesso nel Progetto AETERNA?,
Difficulty: facile
index: 184, Question: Quale percentuale minima di disponibilità deve garantire un provider cloud secondo gli SLA del Progetto AETERNA?,
Difficulty: facile

In [23]:
df_1 = pd.read_csv("./risultati_eval_GPT4.1.csv")
# df_2 = pd.read_csv("./TOADD.csv")

In [ ]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
df_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          20 non-null     str
 1   groundtruth                       20 non-null     str
 2   difficulty                        20 non-null     str
 3   response                          20 non-null     str
 4   scores                            20 non-null     str
 5   sources                           20 non-null     str
 6   judge_score                       20 non-null     float64
 7   noise_sensitivity(mode=relevant)  20 non-null     float64
 8   noise_sensitivity                 1 non-null      float64
dtypes: float64(3), str(6)
memory usage: 94.0 KB

In [ ]:
df_2 = df_2.drop("noise_sensitivity", axis=1)
# df_2 = df_2[:10]

# df_2.dropna(axis=0, how="any", inplace=True)
df_2.info()
# df_2.to_csv("./RIUGHT_risultati_eval_GPT4.1.csv", index=False)
# df_2.iloc[11]

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          20 non-null     str
 1   groundtruth                       20 non-null     str
 2   difficulty                        20 non-null     str
 3   response                          20 non-null     str
 4   scores                            20 non-null     str
 5   sources                           20 non-null     str
 6   judge_score                       20 non-null     float64
 7   noise_sensitivity(mode=relevant)  20 non-null     float64
dtypes: float64(2), str(6)
memory usage: 93.8 KB

In [ ]:
df_finale = df_1.copy()
df_finale["noise_sensitivity(mode=relevant)"] = df_2["noise_sensitivity(mode=relevant)"]
# df_finale["answer_relevancy"] = df_2["answer_relevancy"]
colonne_desiderate = [
    "question", "groundtruth", "difficulty", "response", "scores", 
    "judge_score", "answer_correctness", "semantic_similarity", "faithfulness", 
    "context_recall", "context_precision", "answer_relevancy", "noise_sensitivity(mode=relevant)"
]
df_finale = df_finale[colonne_desiderate]
df_finale.to_csv("./TEMP_risultati_eval_GPT4.1.csv", index=False)
df_finale.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          20 non-null     str
 1   groundtruth                       20 non-null     str
 2   difficulty                        20 non-null     str
 3   response                          20 non-null     str
 4   scores                            20 non-null     str
 5   judge_score                       20 non-null     float64
 6   answer_correctness                20 non-null     float64
 7   semantic_similarity               20 non-null     float64
 8   faithfulness                      20 non-null     float64
 9   context_recall                    20 non-null     float64
 10  context_precision                 20 non-null     float64
 11  answer_relevancy                  20 non-null     float64
 12  noise_sensitivity(mode=relevant)  20 non-null     float64
dtypes: float64(8), str(5)
memory usage: 57.7 KB

# Metrics values

In [ ]:
import pandas as pd

In [ ]:
METRICS = [
    "answer_correctness",
    "semantic_similarity",
    "faithfulness",
    "context_recall",
    "context_precision",
    "answer_relevancy"
]

In [ ]:
df = pd.read_csv("./risultati_eval_GPT4.1.csv")

In [ ]:
insufficienti = df["judge_score"] < 0.5

df.loc[insufficienti, METRICS] = 0.0
df.loc[insufficienti, "noise_sensitivity(mode=relevant)"] = 1.0
        
df.describe()

,judge_score,answer_correctness,semantic_similarity,faithfulness,context_recall,context_precision,answer_relevancy,noise_sensitivity(mode=relevant)
count,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,0.725000,0.570796,0.683554,0.474998,0.542045,0.562500,0.698378,0.231243
std,0.291322,0.271950,0.351608,0.304347,0.441790,0.443335,0.416586,0.350340
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.750000,0.445978,0.619402,0.293062,0.068182,0.000000,0.623947,0.000000
50%,0.750000,0.661874,0.878577,0.481379,0.625000,0.541667,0.901593,0.083333
75%,1.000000,0.721006,0.895866,0.683171,1.000000,1.000000,0.966859,0.273511
max,1.000000,0.940756,0.989981,1.000000,1.000000,1.000000,1.000000,1.000000

   # Reranking

In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv("./risultati_gen_reranking_con_judge.csv")

In [ ]:
for row in df.itertuples():
    if row.judge_score < 0.5:
        print(f"index: {row.Index}, Question: {row.question},\nDifficulty: {row.difficulty}")

index: 23, Question: Qual è il costo stimato per l’implementazione del Multi-Radio Routing Engine (MRRE) su ciascun H-Node in ambiente urbano?,
Difficulty: impossibile
index: 40, Question: Quale protocollo viene utilizzato in AETERNA principalmente per il controllo in tempo reale di attuatori come l’illuminazione pubblica e gli switch energetici?,
Difficulty: facile
index: 160, Question: Quale strumento viene utilizzato per automatizzare i test sulle API RESTful nella piattaforma AETERNA?,
Difficulty: facile
index: 168, Question: Quale strumento viene utilizzato per la simulazione di dipendenze esterne non disponibili o non ancora sviluppate durante il testing di integrazione nel progetto AETERNA?,
Difficulty: facile
index: 176, Question: Quale strumento viene utilizzato per il caching distribuito dei dati ad alta frequenza di accesso nel Progetto AETERNA?,
Difficulty: facile

In [18]:
df = pd.read_csv("./FINALE_reranking_eval.csv")

In [24]:
# df.loc[insufficienti, METRICS] = 0.0
# df.loc[insufficienti, "noise_sensitivity(mode=relevant)"] = 1.0
        
# df.describe()

In [20]:
df_2 = pd.read_csv("./NS_risultati_eval_reranking.csv")
df_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 10 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          20 non-null     str
 1   groundtruth                       20 non-null     str
 2   difficulty                        20 non-null     str
 3   response                          20 non-null     str
 4   scores                            20 non-null     str
 5   sources_before_reranking          20 non-null     str
 6   sources_after_reranking           20 non-null     str
 7   judge_score                       20 non-null     float64
 8   noise_sensitivity(mode=relevant)  20 non-null     float64
 9   sources                           20 non-null     str
dtypes: float64(2), str(8)
memory usage: 475.4 KB

In [ ]:
# df.dropna(axis=0, how="any", inplace=True)
# df.to_csv("./SECONDI_risultati_eval_GPT4.1.csv", index=False)

In [21]:
df_finale = df.copy()
df_finale["noise_sensitivity(mode=relevant)"] = df_2["noise_sensitivity(mode=relevant)"]
# df_finale["answer_relevancy"] = df_2["answer_relevancy"]
colonne_desiderate = [
    "question", "groundtruth", "difficulty", "response", "scores", "sources_before_reranking",
    "sources_after_reranking","judge_score", "answer_correctness", "semantic_similarity", "faithfulness", 
    "context_recall","context_precision", "answer_relevancy", "noise_sensitivity(mode=relevant)"
    # , "noise_sensitivity(mode=relevant)"
]
df_finale = df_finale[colonne_desiderate]
df_finale.to_csv("./evalutation_reranking_eval.csv", index=False)
df_finale.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 15 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          20 non-null     str
 1   groundtruth                       20 non-null     str
 2   difficulty                        20 non-null     str
 3   response                          20 non-null     str
 4   scores                            20 non-null     str
 5   sources_before_reranking          20 non-null     str
 6   sources_after_reranking           20 non-null     str
 7   judge_score                       20 non-null     float64
 8   answer_correctness                20 non-null     float64
 9   semantic_similarity               20 non-null     float64
 10  faithfulness                      20 non-null     float64
 11  context_recall                    20 non-null     float64
 12  context_precision                 20 non-null     float64
 13  answer_relevancy                  20 non-null     float64
 14  noise_sensitivity(mode=relevant)  20 non-null     float64
dtypes: float64(8), str(7)
memory usage: 434.9 KB

In [25]:
df_finale.describe()

,judge_score,answer_correctness,semantic_similarity,faithfulness,context_recall,context_precision,answer_relevancy,noise_sensitivity(mode=relevant)
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,0.83750,0.667600,0.722959,0.690293,0.721591,0.645833,0.678738,0.217037
std,0.12234,0.185963,0.314497,0.289758,0.381481,0.425670,0.407506,0.251283
min,0.75000,0.238497,0.156866,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.75000,0.570142,0.640330,0.500000,0.333333,0.250000,0.584859,0.000000
50%,0.75000,0.661266,0.891087,0.661111,1.000000,0.833333,0.875938,0.158824
75%,1.00000,0.793490,0.919841,1.000000,1.000000,1.000000,0.942025,0.333333
max,1.00000,0.997553,0.990212,1.000000,1.000000,1.000000,1.000000,1.000000

In [27]:
df_finale

,question,groundtruth,difficulty,response,scores,sources_before_reranking,sources_after_reranking,judge_score,answer_correctness,semantic_similarity,faithfulness,context_recall,context_precision,answer_relevancy,noise_sensitivity(mode=relevant)
0,Qual è il periodo minimo di autonomia operativ...,Ogni micro-grid deve essere in grado di operar...,facile,"Secondo lo standard Kyoto 2.0, il periodo mini...","[0.997707724571228, 0.12254319339990616, 0.083...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_01_visione_gl...,0.75,0.569673,0.778692,1.000000,1.000000,1.000000,1.000000,1.000000
1,In che modo il protocollo Bit-Energy integra l...,Il protocollo Bit-Energy integra la componente...,media,Il protocollo Bit-Energy integra la componente...,"[0.4398498237133026, 0.27191218733787537, 0.19...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_01_visione_gl...,0.75,0.909110,0.942562,0.818182,0.750000,0.583333,0.934977,0.090909
2,Quali sono le fasi principali del processo di ...,Le fasi principali del processo di ottimizzazi...,difficile,"Sulla base del contesto fornito, le fasi princ...","[0.9495925903320312, 0.7974904775619507, 0.527...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_01_visione_gl...,0.75,0.635041,0.893106,0.500000,0.333333,0.000000,0.843459,0.050000
3,Qual è il costo medio di implementazione di un...,L'informazione non è disponibile nel testo,impossibile,Il contesto fornito non riporta informazioni s...,"[0.010046163573861122, 0.008939716033637524, 0...",[Document(id='synthetic_data_AETERNA\\Volume_1...,['synthetic_data_AETERNA\\Volume_02_architettu...,1.00,0.789217,0.156866,1.000000,1.000000,0.833333,0.000000,0.000000
4,Qual è la quota minima di energia garantita a ...,La quota minima di energia garantita a ciascun...,facile,"Secondo la policy Kyoto 2.0, durante una fines...","[0.9987035989761353, 0.9693052768707275, 0.498...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_01_visione_gl...,0.75,0.878096,0.940957,1.000000,1.000000,1.000000,0.992828,0.571429
5,In che modo il framework AETERNA garantisce la...,Il framework AETERNA garantisce la priorità en...,media,Il framework AETERNA garantisce la priorità en...,"[0.9885398745536804, 0.9846306443214417, 0.947...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_12_interfacci...,0.75,0.450838,0.865850,0.562500,0.000000,0.000000,0.875705,0.117647
6,Quali sono i passaggi e i meccanismi tecnici c...,"Il cittadino, dopo essersi autenticato tramite...",difficile,Ecco i passaggi e i meccanismi tecnici che per...,"[0.037725288420915604, 0.028410375118255615, 0...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_01_visione_gl...,0.75,0.570299,0.811807,0.935484,1.000000,1.000000,0.787413,0.433333
7,Qual è il costo medio di implementazione di un...,L'informazione non è disponibile nel testo,impossibile,Il contesto fornito non include informazioni r...,"[0.06538699567317963, 0.03878386318683624, 0.0...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_02_architettu...,1.00,0.238497,0.203988,0.500000,1.000000,0.833333,0.000000,0.333333
8,Quali sono i livelli di Purezza Verde che perm...,"Solo le fonti classificate ai livelli 8, 9 e 1...",facile,"Solo le fonti classificate ai livelli 8, 9 e 1...","[0.9469287395477295, 0.8815125226974487, 0.731...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_01_visione_gl...,0.75,0.862667,0.879240,0.000000,1.000000,1.000000,0.793146,0.000000
9,In che modo la Coscienza di Rete del Progetto ...,La Coscienza di Rete del Progetto AETERNA inte...,media,La Coscienza di Rete del Progetto AETERNA inte...,"[0.9736599326133728, 0.9423561096191406, 0.697...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_01_visione_gl...,0.75,0.624457,0.897827,0.562500,0.333333,0.000000,0.779812,0.000000
10,Quali sono le principali strategie e component...,Le principali strategie e componenti tecnologi...,difficile,Le principali strategie e componenti tecnologi...,"[0.9766834378242493, 0.9765030145645142, 0.968...",[Document(id='synthetic_data_AETERNA\\Volume_1...,['synthetic_data_AETERNA\\Volume_02_architettu...,0.75,0.779264,0.923509,0.500000,0.181818,0.833333,0.963167,0.277778
11,Qual è il costo medio di produzione di un H-No...,L'informazione non è disponibile nel testo,impossibile,Il contesto fornito non include informazioni r...,"[0.1691206991672516, 0.1451481729745865, 0.106...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_08_gestione_d...,1.00,0.644800,0.179199,1.000000,1.000000,1.000000,0.000000,0.333333
12,Quale componente del livello Fog gestisce la f...,Il componente del livello Fog che gestisce la ...,facile,La componente del livello Fog che gestisce la ...,"[0.9996104836463928, 0.05688650161027908, 0.03...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_02_architettu...,1.00,0.997553,0.990212,1.000000,1.000000,1.000000,0.985074,0.000000
13,In che modo l’adozione di database vettoriali ...,L’adozione di database vettoriali nel livello ...,media,L’adozione di database vettoriali nel livello ...,"[0.978198766708374, 0.9086626172065735, 0.7029...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_02_architettu...,0.75,0.677732,0.910929,0.722222,0.500000,1.000000,0.906185,0.277778
14,Quali sono le principali strategie multilivell...,Le principali strategie multilivello adottate ...,difficile,Le principali strategie multilivello adottate ...,"[0.9865041971206665, 0.9840635061264038, 0.978...",[Document(id='synthetic_data_AETERNA\\Volume_1...,['synthetic_data_AETERNA\\Volume_10_gestione_d...,0.75,0.451473,0.900230,0.600000,0.000000,0.333333,0.876171,0.200000
15,Qual è il costo medio di implementazione di un...,L'informazione non è disponibile nel testo,impossibile,Il contesto fornito non include informazioni r...,"[0.1285047084093094, 0.05563432350754738, 0.04...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_02_architettu...,1.00,0.431005,0.224022,0.500000,1.000000,0.500000,0.000000,0.333333
16,Qual è il ruolo del Fog Leader durante la moda...,"Durante la modalità Fog-Independence, il Fog L...",facile,"Durante la modalità Fog-Independence, il Fog L...","[0.832581639289856, 0.06581543385982513, 0.040...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_02_architettu...,0.75,0.691193,0.918619,0.437500,1.000000,1.000000,0.930959,0.000000
17,In che modo la scelta di GraphQL come protocol...,La scelta di GraphQL come protocollo di esposi...,media,La scelta di GraphQL come protocollo di esposi...,"[0.9945526719093323, 0.9927645325660706, 0.987...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_02_architettu...,1.00,0.717107,0.927250,0.894737,1.000000,1.000000,0.996153,0.052632
18,Quali sono le principali fasi e i meccanismi d...,Le principali fasi del processo di provisionin...,difficile,"Sulla base del contesto fornito, le principali...","[0.9949086308479309, 0.9870443940162659, 0.984...",[Document(id='synthetic_data_AETERNA\\Volume_1...,['synthetic_data_AETERNA\\Volume_15_formazione...,0.75,0.627672,0.889068,0.272727,0.333333,0.000000,0.909703,0.269231
19,Qual è il costo medio di implementazione del p...,L'informazione non è disponibile nel testo,impossibile,Il contesto fornito non include informazioni r...,"[0.031636714935302734, 0.0067855119705200195, ...",[Document(id='synthetic_data_AETERNA\\Volume_0...,['synthetic_data_AETERNA\\Volume_02_architettu...,1.00,0.806312,0.225246,1.000000,1.000000,0.000000,0.000000,0.000000