# Generation

In [81]:
import pandas as pd

In [82]:
df = pd.read_csv('./risultati/AETERNA/prima_generazione/gen_GPT-4.1.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   question            200 non-null    str
 1   groundtruth         200 non-null    str
 2   difficulty          200 non-null    str
 3   response            200 non-null    str
 4   scores              200 non-null    str
 5   sources             200 non-null    str
 6   retrieved_contexts  200 non-null    str
dtypes: str(7)
memory usage: 777.2 KB

In [83]:
df.describe()

,question,groundtruth,difficulty,response,scores,sources,retrieved_contexts
count,200,200,200,200,200,200,200
unique,200,152,4,200,200,199,199
top,Qual è il periodo minimo di autonomia operativ...,L'informazione non è disponibile nel testo,facile,"Secondo lo standard Kyoto 2.0, la micro-grid d...","[0.33877503871917725, 0.39287227392196655, 0.4...","[""Volume_03_specifiche_hardware_dell'h-node.md...",['Il modulo HSM (Hardware Security Module) rap...
freq,1,48,50,1,1,2,2

In [84]:
df.head()

,question,groundtruth,difficulty,response,scores,sources,retrieved_contexts
0,Qual è il periodo minimo di autonomia operativ...,Ogni micro-grid deve essere in grado di operar...,facile,"Secondo lo standard Kyoto 2.0, la micro-grid d...","[0.33877503871917725, 0.39287227392196655, 0.4...",['Volume_01_visione_globale_e_filosofia_di_aet...,['Bassa Trasparenza Operativa: Impossibilità d...
1,In che modo il protocollo Bit-Energy integra l...,Il protocollo Bit-Energy integra la componente...,media,Il protocollo Bit-Energy integra la componente...,"[0.3185817003250122, 0.3217049241065979, 0.352...",['Volume_01_visione_globale_e_filosofia_di_aet...,['Il protocollo Bit-Energy prevede che ogni tr...
2,Quali sono le fasi principali del processo di ...,Le fasi principali del processo di ottimizzazi...,difficile,Le fasi principali del processo di ottimizzazi...,"[0.200680673122406, 0.28687894344329834, 0.287...",['Volume_01_visione_globale_e_filosofia_di_aet...,"['AETERNA, attraverso la sua architettura mult..."
3,Qual è il costo medio di implementazione di un...,L'informazione non è disponibile nel testo,impossibile,Il costo medio di implementazione di un H-Node...,"[0.3147541284561157, 0.36050379276275635, 0.37...",['Volume_11_integrazione_con_le_energie_rinnov...,['Nel quadro architetturale del Progetto AETER...
4,Qual è la quota minima di energia garantita a ...,La quota minima di energia garantita a ciascun...,facile,"Secondo la policy Kyoto 2.0, la quota minima d...","[0.35863882303237915, 0.40705418586730957, 0.4...",['Volume_01_visione_globale_e_filosofia_di_aet...,['2. Flusso Decisionale e Moduli Coinvolti\n\n...

# Evaluation

In [85]:
import pandas as pd

In [86]:
df = pd.read_csv('./risultati/AETERNA/prima_generazione/eval_Qwen.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          50 non-null     str
 1   groundtruth                       50 non-null     str
 2   difficulty                        50 non-null     str
 3   response                          50 non-null     str
 4   scores                            50 non-null     str
 5   sources                           50 non-null     str
 6   answer_correctness                48 non-null     float64
 7   faithfulness                      48 non-null     float64
 8   answer_relevancy                  49 non-null     float64
 9   context_precision                 49 non-null     float64
 10  context_recall                    49 non-null     float64
 11  noise_sensitivity(mode=relevant)  49 non-null     float64
 12  semantic_similarity               50 non-null     float64
dtypes: float64(7), str(6)
memory usage: 183.8 KB

In [87]:
df.head()

,question,groundtruth,difficulty,response,scores,sources,answer_correctness,faithfulness,answer_relevancy,context_precision,context_recall,noise_sensitivity(mode=relevant),semantic_similarity
0,Qual è il periodo minimo di autonomia operativ...,Ogni micro-grid deve essere in grado di operar...,['facile'],"Secondo lo standard Kyoto 2.0, la micro-grid d...","[0.33877503871917725, 0.39287227392196655, 0.4...",['Bassa Trasparenza Operativa: Impossibilità d...,0.598988,1.000000,0.863122,1.0,1.000000,1.0,0.895952
1,In che modo il protocollo Bit-Energy integra l...,Il protocollo Bit-Energy integra la componente...,['media'],Il protocollo Bit-Energy integra la componente...,"[0.3185817003250122, 0.3217049241065979, 0.352...",['Il protocollo Bit-Energy prevede che ogni tr...,0.512293,0.846154,0.892714,1.0,0.750000,0.6,0.895326
2,Quali sono le fasi principali del processo di ...,Le fasi principali del processo di ottimizzazi...,['difficile'],Le fasi principali del processo di ottimizzazi...,"[0.200680673122406, 0.28687894344329834, 0.287...","['AETERNA, attraverso la sua architettura mult...",0.448764,0.230769,0.842521,0.0,0.307692,0.0,0.773781
3,Qual è il costo medio di implementazione di un...,L'informazione non è disponibile nel testo,['impossibile'],Il costo medio di implementazione di un H-Node...,"[0.3147541284561157, 0.36050379276275635, 0.37...",['Nel quadro architetturale del Progetto AETER...,0.018242,0.214286,0.000000,1.0,1.000000,0.0,0.072970
4,Qual è la quota minima di energia garantita a ...,La quota minima di energia garantita a ciascun...,['facile'],"Secondo la policy Kyoto 2.0, la quota minima d...","[0.35863882303237915, 0.40705418586730957, 0.4...",['2. Flusso Decisionale e Moduli Coinvolti\n\n...,0.515475,0.500000,0.863306,1.0,1.000000,0.0,0.861901

In [88]:
df = pd.read_csv('./risultati/AETERNA/prima_generazione/eval_GPT-4.1.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          200 non-null    str
 1   groundtruth                       200 non-null    str
 2   difficulty                        200 non-null    str
 3   response                          200 non-null    str
 4   scores                            200 non-null    str
 5   sources                           200 non-null    str
 6   faithfulness                      200 non-null    float64
 7   answer_relevancy                  200 non-null    float64
 8   context_precision                 200 non-null    float64
 9   context_recall                    200 non-null    float64
 10  noise_sensitivity(mode=relevant)  195 non-null    float64
 11  semantic_similarity               200 non-null    float64
 12  answer_correctness                200 non-null    float64
dtypes: float64(7), str(6)
memory usage: 750.7 KB

In [89]:
df.iloc[0:50].describe()

,faithfulness,answer_relevancy,context_precision,context_recall,noise_sensitivity(mode=relevant),semantic_similarity,answer_correctness
count,50.000000,50.000000,50.000000,50.000000,47.000000,50.000000,50.000000
mean,0.411237,0.777642,0.633333,0.675356,0.151814,0.619371,0.410196
std,0.372910,0.324410,0.437409,0.402586,0.288013,0.327984,0.253722
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.010828,0.002707
25%,0.000000,0.821425,0.000000,0.250000,0.000000,0.337819,0.301946
50%,0.366667,0.894234,0.916667,1.000000,0.000000,0.796181,0.420038
75%,0.738971,0.958744,1.000000,1.000000,0.184659,0.856180,0.538980
max,1.000000,1.000000,1.000000,1.000000,1.000000,0.911091,0.909591

In [90]:
df = pd.read_csv('./risultati/AETERNA/prima_generazione/eval_GPT-5-mini.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          50 non-null     str
 1   groundtruth                       50 non-null     str
 2   difficulty                        50 non-null     str
 3   response                          50 non-null     str
 4   scores                            50 non-null     str
 5   sources                           50 non-null     str
 6   retrieved_contexts                50 non-null     str
 7   answer_correctness                25 non-null     float64
 8   faithfulness                      25 non-null     float64
 9   context_precision                 25 non-null     float64
 10  answer_relevancy                  25 non-null     float64
 11  context_recall                    25 non-null     float64
 12  noise_sensitivity(mode=relevant)  24 non-null     float64
 13  semantic_similarity               50 non-null     float64
dtypes: float64(7), str(7)
memory usage: 192.7 KB

In [91]:
df.head()

,question,groundtruth,difficulty,response,scores,sources,retrieved_contexts,answer_correctness,faithfulness,context_precision,answer_relevancy,context_recall,noise_sensitivity(mode=relevant),semantic_similarity
0,Qual è il periodo minimo di autonomia operativ...,Ogni micro-grid deve essere in grado di operar...,facile,"Secondo lo standard Kyoto 2.0, la micro-grid d...","[0.33877503871917725, 0.39287227392196655, 0.4...",['Volume_01_visione_globale_e_filosofia_di_aet...,['Bassa Trasparenza Operativa: Impossibilità d...,0.973988,1.000000,1.0,0.842343,1.000000,1.000000,0.895952
1,In che modo il protocollo Bit-Energy integra l...,Il protocollo Bit-Energy integra la componente...,media,Il protocollo Bit-Energy integra la componente...,"[0.3185817003250122, 0.3217049241065979, 0.352...",['Volume_01_visione_globale_e_filosofia_di_aet...,['Il protocollo Bit-Energy prevede che ogni tr...,0.680353,0.944444,1.0,0.858187,0.750000,0.277778,0.895326
2,Quali sono le fasi principali del processo di ...,Le fasi principali del processo di ottimizzazi...,difficile,Le fasi principali del processo di ottimizzazi...,"[0.200680673122406, 0.28687894344329834, 0.287...",['Volume_01_visione_globale_e_filosofia_di_aet...,"['AETERNA, attraverso la sua architettura mult...",0.463445,0.400000,1.0,0.774638,0.769231,0.000000,0.773781
3,Qual è il costo medio di implementazione di un...,L'informazione non è disponibile nel testo,impossibile,Il costo medio di implementazione di un H-Node...,"[0.3147541284561157, 0.36050379276275635, 0.37...",['Volume_11_integrazione_con_le_energie_rinnov...,['Nel quadro architetturale del Progetto AETER...,0.018242,0.000000,1.0,0.000000,1.000000,0.000000,0.072970
4,Qual è la quota minima di energia garantita a ...,La quota minima di energia garantita a ciascun...,facile,"Secondo la policy Kyoto 2.0, la quota minima d...","[0.35863882303237915, 0.40705418586730957, 0.4...",['Volume_01_visione_globale_e_filosofia_di_aet...,['2. Flusso Decisionale e Moduli Coinvolti\n\n...,0.715475,0.666667,1.0,0.740674,1.000000,0.166667,0.861901

In [92]:
df = pd.read_csv('./risultati/AETERNA/prima_generazione/eval_GPT-4.1_BGE.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          20 non-null     str
 1   retrieved_contexts                20 non-null     str
 2   response                          20 non-null     str
 3   reference                         20 non-null     str
 4   answer_correctness                20 non-null     float64
 5   faithfulness                      20 non-null     float64
 6   context_precision                 20 non-null     float64
 7   answer_relevancy                  20 non-null     float64
 8   context_recall                    20 non-null     float64
 9   noise_sensitivity(mode=relevant)  20 non-null     float64
 10  semantic_similarity               20 non-null     float64
dtypes: float64(7), str(4)
memory usage: 72.7 KB

In [93]:
df.head()

,question,retrieved_contexts,response,reference,answer_correctness,faithfulness,context_precision,answer_relevancy,context_recall,noise_sensitivity(mode=relevant),semantic_similarity
0,Qual è il periodo minimo di autonomia operativ...,['Bassa Trasparenza Operativa: Impossibilità d...,"Secondo lo standard Kyoto 2.0, la micro-grid d...",Ogni micro-grid deve essere in grado di operar...,0.815588,1.000000,1.0,0.901366,1.000000,1.000000,0.862352
1,In che modo il protocollo Bit-Energy integra l...,['Il protocollo Bit-Energy prevede che ogni tr...,Il protocollo Bit-Energy integra la componente...,Il protocollo Bit-Energy integra la componente...,0.551691,0.818182,1.0,0.928163,0.750000,0.454545,0.956766
2,Quali sono le fasi principali del processo di ...,"['AETERNA, attraverso la sua architettura mult...",Le fasi principali del processo di ottimizzazi...,Le fasi principali del processo di ottimizzazi...,0.476852,0.250000,0.0,0.885153,0.153846,0.125000,0.868946
3,Qual è il costo medio di implementazione di un...,['Nel quadro architetturale del Progetto AETER...,Il costo medio di implementazione di un H-Node...,L'informazione non è disponibile nel testo,0.076342,0.000000,1.0,0.954089,1.000000,0.000000,0.305368
4,Qual è la quota minima di energia garantita a ...,['2. Flusso Decisionale e Moduli Coinvolti\n\n...,"Secondo la policy Kyoto 2.0, la quota minima d...",La quota minima di energia garantita a ciascun...,0.669951,0.666667,1.0,0.896319,1.000000,0.000000,0.879806

# LLM-as-a-Judge

In [94]:
import pandas as pd

In [95]:
df = pd.read_csv("./risultati/AETERNA/LLM-as-a-judge/gen_GPT4.1_con_judge.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   question            200 non-null    str
 1   groundtruth         200 non-null    str
 2   difficulty          200 non-null    str
 3   response            200 non-null    str
 4   scores              200 non-null    str
 5   sources             200 non-null    str
 6   retrieved_contexts  200 non-null    str
 7   judge_score         200 non-null    float64
dtypes: float64(1), str(7)
memory usage: 953.7 KB

In [96]:
df.head()

,question,groundtruth,difficulty,response,scores,sources,retrieved_contexts,judge_score
0,Qual è il periodo minimo di autonomia operativ...,Ogni micro-grid deve essere in grado di operar...,facile,Il periodo minimo di autonomia operativa richi...,"[0.33877503871917725, 0.48011720180511475, 0.4...",['synthetic_data_AETERNA\\Volume_01_visione_gl...,['Bassa Trasparenza Operativa: Impossibilità d...,0.75
1,In che modo il protocollo Bit-Energy integra l...,Il protocollo Bit-Energy integra la componente...,media,Il protocollo Bit-Energy integra la componente...,"[0.3185817003250122, 0.3217049241065979, 0.352...",['synthetic_data_AETERNA\\Volume_01_visione_gl...,['Il protocollo Bit-Energy prevede che ogni tr...,0.75
2,Quali sono le fasi principali del processo di ...,Le fasi principali del processo di ottimizzazi...,difficile,Le fasi principali del processo di ottimizzazi...,"[0.200680673122406, 0.28687894344329834, 0.287...",['synthetic_data_AETERNA\\Volume_01_visione_gl...,"['AETERNA, attraverso la sua architettura mult...",0.75
3,Qual è il costo medio di implementazione di un...,L'informazione non è disponibile nel testo,impossibile,"Sulla base del contesto fornito, non sono pres...","[0.3147541284561157, 0.36050379276275635, 0.37...",['synthetic_data_AETERNA\\Volume_11_integrazio...,['Nel quadro architetturale del Progetto AETER...,1.00
4,Qual è la quota minima di energia garantita a ...,La quota minima di energia garantita a ciascun...,facile,"Secondo la policy Kyoto 2.0, durante una fines...","[0.35863882303237915, 0.40705418586730957, 0.4...",['synthetic_data_AETERNA\\Volume_01_visione_gl...,['2. Flusso Decisionale e Moduli Coinvolti\n\n...,0.75

In [97]:
for row in df.itertuples():
    if row.judge_score < 0.5:
        print(f"{row.Index}. {row.question},\nDifficulty: {row.difficulty} - Judge score: {row.judge_score}")

11. Qual è il costo medio di produzione di un H-Node Edge dotato di micro-controller ARM Cortex-M33 e Secure Enclave?,
Difficulty: impossibile - Judge score: 0.0
15. Qual è il costo medio di implementazione di un modulo Pulse Master su ciascun H-Node in una micro-rete energetica conforme alle policy Kyoto 2.0?,
Difficulty: impossibile - Judge score: 0.0
59. Qual è la versione minima di MATLAB/Simulink richiesta per garantire la compatibilità con i moduli digital twin H-Node nel framework di simulazione AETERNA?,
Difficulty: impossibile - Judge score: 0.25
64. Quale tipo di autenticazione multifattoriale è richiesto per un amministratore nella piattaforma AETERNA?,
Difficulty: facile - Judge score: 0.0
80. Quali sono i tre organi principali che formalizzano la governance della rete AETERNA?,
Difficulty: facile - Judge score: 0.25
131. Qual è il costo medio di implementazione per nodo degli agenti di telemetria containerizzati nel Progetto AETERNA, considerando sia la componente hardware che quella software?,
Difficulty: impossibile - Judge score: 0.0
132. Quale standard viene utilizzato per la normalizzazione dei dati nella fase di pre-processing della pipeline di analisi predittiva dei guasti in AETERNA?,
Difficulty: facile - Judge score: 0.0
155. Qual è il costo medio di implementazione per nodo domestico (H-Node) dei sensori IoT multi-parametrici utilizzati nel Progetto AETERNA?,
Difficulty: impossibile - Judge score: 0.25
156. Quale piattaforma viene utilizzata per la raccolta e gestione dei ticket di supporto nel Progetto AETERNA?,
Difficulty: facile - Judge score: 0.0
160. Quale strumento viene utilizzato per automatizzare i test sulle API RESTful nella piattaforma AETERNA?,
Difficulty: facile - Judge score: 0.0
176. Quale strumento viene utilizzato per il caching distribuito dei dati ad alta frequenza di accesso nel Progetto AETERNA?,
Difficulty: facile - Judge score: 0.0
184. Quale percentuale minima di disponibilità deve garantire un provider cloud secondo gli SLA del Progetto AETERNA?,
Difficulty: facile - Judge score: 0.0

In [98]:
METRICS = [
    "answer_correctness",
    "semantic_similarity",
    "faithfulness",
    "context_recall",
    "context_precision",
    "answer_relevancy"
]

In [99]:
df = pd.read_csv("./risultati/AETERNA/LLM-as-a-judge/eval_GPT4.1_con_judge.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          50 non-null     str
 1   groundtruth                       50 non-null     str
 2   difficulty                        50 non-null     str
 3   response                          50 non-null     str
 4   scores                            50 non-null     str
 5   judge_score                       50 non-null     float64
 6   answer_correctness                50 non-null     float64
 7   semantic_similarity               50 non-null     float64
 8   faithfulness                      50 non-null     float64
 9   context_recall                    50 non-null     float64
 10  context_precision                 50 non-null     float64
 11  answer_relevancy                  50 non-null     float64
 12  noise_sensitivity(mode=relevant)  49 non-null     float64
dtypes: float64(8), str(5)
memory usage: 133.3 KB

In [100]:
insufficienti = df["judge_score"] < 0.5

df.loc[insufficienti, METRICS] = 0.0
df.loc[insufficienti, "noise_sensitivity(mode=relevant)"] = 1.0
        
df.describe()

,judge_score,answer_correctness,semantic_similarity,faithfulness,context_recall,context_precision,answer_relevancy,noise_sensitivity(mode=relevant)
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,49.000000
mean,0.820000,0.597865,0.681446,0.595952,0.602399,0.601667,0.705022,0.204053
std,0.220389,0.215316,0.311135,0.300881,0.437335,0.409042,0.403720,0.299406
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.750000,0.483076,0.542123,0.421345,0.166667,0.333333,0.818568,0.000000
50%,0.750000,0.609200,0.847679,0.604348,0.875000,0.583333,0.901840,0.083333
75%,1.000000,0.722593,0.893518,0.833333,1.000000,1.000000,0.976483,0.272727
max,1.000000,0.996943,0.989981,1.000000,1.000000,1.000000,1.000000,1.000000

   # Reranking con reranker esterno

In [101]:
import pandas as pd

In [102]:
df = pd.read_csv('./risultati/AETERNA/reranker-esterno/gen_reranking.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   question                  200 non-null    str
 1   groundtruth               200 non-null    str
 2   difficulty                200 non-null    str
 3   response                  200 non-null    str
 4   scores                    200 non-null    str
 5   sources_before_reranking  200 non-null    str
 6   sources_after_reranking   200 non-null    str
 7   retrieved_contexts        200 non-null    str
dtypes: str(8)
memory usage: 4.6 MB

In [103]:
df = pd.read_csv("./risultati/AETERNA/reranker-esterno/gen_reranking_con_judge.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   question                  200 non-null    str
 1   groundtruth               200 non-null    str
 2   difficulty                200 non-null    str
 3   response                  200 non-null    str
 4   scores                    200 non-null    str
 5   sources_before_reranking  200 non-null    str
 6   sources_after_reranking   200 non-null    str
 7   retrieved_contexts        200 non-null    str
 8   judge_score               200 non-null    float64
dtypes: float64(1), str(8)
memory usage: 4.6 MB

In [104]:
for row in df.itertuples():
    if row.judge_score < 0.5:
        print(f"{row.Index}. {row.question},\nDifficulty: {row.difficulty} - Judge score: {row.judge_score}")

23. Qual è il costo stimato per l’implementazione del Multi-Radio Routing Engine (MRRE) su ciascun H-Node in ambiente urbano?,
Difficulty: impossibile - Judge score: 0.25
40. Quale protocollo viene utilizzato in AETERNA principalmente per il controllo in tempo reale di attuatori come l’illuminazione pubblica e gli switch energetici?,
Difficulty: facile - Judge score: 0.25
160. Quale strumento viene utilizzato per automatizzare i test sulle API RESTful nella piattaforma AETERNA?,
Difficulty: facile - Judge score: 0.0
168. Quale strumento viene utilizzato per la simulazione di dipendenze esterne non disponibili o non ancora sviluppate durante il testing di integrazione nel progetto AETERNA?,
Difficulty: facile - Judge score: 0.0
176. Quale strumento viene utilizzato per il caching distribuito dei dati ad alta frequenza di accesso nel Progetto AETERNA?,
Difficulty: facile - Judge score: 0.0

In [105]:
METRICS = [
    "answer_correctness",
    "semantic_similarity",
    "faithfulness",
    "context_recall",
    "context_precision",
    "answer_relevancy"
]

In [106]:
df = pd.read_csv("./risultati/AETERNA/reranker-esterno/eval_reranking.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 15 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          50 non-null     str
 1   groundtruth                       50 non-null     str
 2   difficulty                        50 non-null     str
 3   response                          50 non-null     str
 4   scores                            50 non-null     str
 5   sources_before_reranking          50 non-null     str
 6   sources_after_reranking           50 non-null     str
 7   judge_score                       50 non-null     float64
 8   answer_correctness                50 non-null     float64
 9   semantic_similarity               50 non-null     float64
 10  faithfulness                      50 non-null     float64
 11  context_recall                    50 non-null     float64
 12  context_precision                 50 non-null     float64
 13  answer_relevancy                  50 non-null     float64
 14  noise_sensitivity(mode=relevant)  49 non-null     float64
dtypes: float64(8), str(7)
memory usage: 1.1 MB

In [107]:
insufficienti = df["judge_score"] < 0.5

df.loc[insufficienti, METRICS] = 0.0
df.loc[insufficienti, "noise_sensitivity(mode=relevant)"] = 1.0
        
df.describe()

,judge_score,answer_correctness,semantic_similarity,faithfulness,context_recall,context_precision,answer_relevancy,noise_sensitivity(mode=relevant)
count,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,49.000000
mean,0.805000,0.656340,0.683256,0.693692,0.640819,0.580000,0.687045,0.228283
std,0.197497,0.219990,0.325137,0.343875,0.423900,0.433817,0.415206,0.299446
min,0.250000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.750000,0.553488,0.339192,0.500000,0.229167,0.000000,0.194953,0.000000
50%,0.750000,0.642835,0.859044,0.801948,1.000000,0.833333,0.901565,0.090909
75%,1.000000,0.805212,0.908254,1.000000,1.000000,1.000000,0.978756,0.333333
max,1.000000,0.997798,0.991191,1.000000,1.000000,1.000000,1.000000,1.000000

   # Reranking con LLM

In [108]:
import pandas as pd

In [109]:
df = pd.read_csv('./risultati/AETERNA/reranker_LLM/gen_reranker_llm.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   question                  50 non-null     str
 1   groundtruth               50 non-null     str
 2   difficulty                50 non-null     str
 3   response                  50 non-null     str
 4   scores                    50 non-null     str
 5   sources_before_reranking  50 non-null     str
 6   sources_after_reranking   50 non-null     str
 7   retrieved_contexts        50 non-null     str
dtypes: str(8)
memory usage: 1.9 MB

In [110]:
df = pd.read_csv('./risultati/AETERNA/reranker_LLM/gen_reranker_llm_con_judge.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   question                  50 non-null     str
 1   groundtruth               50 non-null     str
 2   difficulty                50 non-null     str
 3   response                  50 non-null     str
 4   scores                    50 non-null     str
 5   sources_before_reranking  50 non-null     str
 6   sources_after_reranking   50 non-null     str
 7   retrieved_contexts        50 non-null     str
 8   judge_score               50 non-null     float64
dtypes: float64(1), str(8)
memory usage: 1.9 MB

In [111]:
for row in df.itertuples():
    if row.judge_score < 0.5:
        print(f"{row.Index}. {row.question},\nDifficulty: {row.difficulty} - Judge score: {row.judge_score}")

In [112]:
METRICS = [
    "answer_correctness",
    "semantic_similarity",
    "faithfulness",
    "context_recall",
    "context_precision",
    "answer_relevancy"
]

In [113]:
df = pd.read_csv("./risultati/AETERNA/reranker_LLM/eval_reranker_llm_con_judge.csv")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 15 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          50 non-null     str
 1   groundtruth                       50 non-null     str
 2   difficulty                        50 non-null     str
 3   response                          50 non-null     str
 4   scores                            50 non-null     str
 5   sources_before_reranking          50 non-null     str
 6   sources_after_reranking           50 non-null     str
 7   judge_score                       50 non-null     float64
 8   answer_correctness                50 non-null     float64
 9   semantic_similarity               50 non-null     float64
 10  faithfulness                      50 non-null     float64
 11  context_recall                    50 non-null     float64
 12  context_precision                 50 non-null     float64
 13  answer_relevancy                  50 non-null     float64
 14  noise_sensitivity(mode=relevant)  43 non-null     float64
dtypes: float64(8), str(7)
memory usage: 1.5 MB

In [114]:
insufficienti = df["judge_score"] < 0.5

df.loc[insufficienti, METRICS] = 0.0
df.loc[insufficienti, "noise_sensitivity(mode=relevant)"] = 1.0
        
df.describe()

,judge_score,answer_correctness,semantic_similarity,faithfulness,context_recall,context_precision,answer_relevancy,noise_sensitivity(mode=relevant)
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000,50.000000,43.000000
mean,0.88500,0.646731,0.735302,0.882909,0.783675,0.753025,0.759956,0.312777
std,0.14472,0.223781,0.304415,0.210059,0.293211,0.287114,0.370248,0.289519
min,0.50000,0.158984,0.090480,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.75000,0.534901,0.596703,0.850204,0.480359,0.580000,0.809120,0.015625
50%,1.00000,0.622049,0.881814,0.961538,1.000000,0.869844,0.941437,0.300000
75%,1.00000,0.787313,0.925316,1.000000,1.000000,0.985119,0.992741,0.436508
max,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# MCP-Server

In [115]:
import pandas as pd

In [116]:
df = pd.read_csv('./risultati/AETERNA/MCP_Server/gen_mcp_server.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   question            50 non-null     str
 1   groundtruth         50 non-null     str
 2   difficulty          50 non-null     str
 3   response            50 non-null     str
 4   scores              50 non-null     str
 5   retrieved_contexts  50 non-null     str
 6   total_hops          50 non-null     int64
dtypes: int64(1), str(6)
memory usage: 563.1 KB

In [117]:
df = pd.read_csv('./risultati/AETERNA/MCP_Server/gen_mcp_server_con_judge.csv')
df.describe()

       total_hops  judge_score
count    50.00000    50.000000
mean      2.84000     0.830000
std       1.16689     0.178142
min       2.00000     0.000000
25%       2.00000     0.750000
50%       2.00000     0.750000
75%       3.00000     1.000000
max       5.00000     1.000000

In [118]:
for row in df.itertuples():
    if row.judge_score < 0.5:
        print(f"{row.Index}. {row.question},\nDifficulty: {row.difficulty} - Judge score: {row.judge_score}")

23. Qual è il costo stimato per l’implementazione del Multi-Radio Routing Engine (MRRE) su ciascun H-Node in ambiente urbano?,
Difficulty: impossibile - Judge score: 0.0

In [119]:
df = pd.read_csv('./risultati/AETERNA/MCP_Server/eval_mcp_server_con_judge.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 14 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   question                          50 non-null     str
 1   groundtruth                       50 non-null     str
 2   difficulty                        50 non-null     str
 3   response                          50 non-null     str
 4   scores                            50 non-null     str
 5   total_hops                        50 non-null     int64
 6   judge_score                       50 non-null     float64
 7   answer_correctness                50 non-null     float64
 8   semantic_similarity               50 non-null     float64
 9   faithfulness                      50 non-null     float64
 10  context_recall                    50 non-null     float64
 11  context_precision                 50 non-null     float64
 12  answer_relevancy                  50 non-null     float64
 13  noise_sensitivity(mode=relevant)  50 non-null     float64
dtypes: float64(8), int64(1), str(5)
memory usage: 138.3 KB

In [120]:
METRICS = [
    "answer_correctness",
    "semantic_similarity",
    "faithfulness",
    "context_recall",
    "context_precision",
    "answer_relevancy"
]

In [121]:
insufficienti = df["judge_score"] < 0.5

df.loc[insufficienti, METRICS] = 0.0
df.loc[insufficienti, "noise_sensitivity(mode=relevant)"] = 1.0
        
df.describe()

,total_hops,judge_score,answer_correctness,semantic_similarity,faithfulness,context_recall,context_precision,answer_relevancy,noise_sensitivity(mode=relevant)
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000,50.00000,50.000000,50.000000
mean,2.84000,0.830000,0.620291,0.793786,0.834912,0.900706,0.86000,0.733271,0.460164
std,1.16689,0.178142,0.240341,0.265163,0.216413,0.211292,0.35051,0.397965,0.296842
min,2.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,2.00000,0.750000,0.463554,0.829502,0.783854,0.931818,1.00000,0.777928,0.256250
50%,2.00000,0.750000,0.641900,0.897187,0.904798,1.000000,1.00000,0.949064,0.507576
75%,3.00000,1.000000,0.760603,0.915661,1.000000,1.000000,1.00000,0.983797,0.636364
max,5.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000